### ISSUE TITLE
Error: "detector2 is not a function" when importing mermaid-zenuml

### ISSUE THREAD

**Issue by reubenfirmin** [mermaid-js/zenuml-core#109]
I'm importing mermaid-zenuml into a kotlinjs project, and get an error when passing it to registerExternalDiagrams:

```
r2 is not a function', message: 'detector2 is not a function', hash: 'TypeError', error: TypeError: detector2 is not a function
    at detectType (webpack-internal:///../../node_modules/me…}error: TypeError: detector2 is not a function
    at detectType (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:2420:22)
    at getDiagramFromText (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:3724:17)
    at Object.render$1 [as render] (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6044:18)
    at eval (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6346:18)
    at new Promise (<anonymous>)
    at performCall (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6345:31)
    at executeQueue (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6314:15)
    at eval (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6361:5)
    at new Promise (<anonymous>)
    at render (webpack-internal:///../../node_modules/mermaid/dist/mermaid-934d9bea.js:6344:10)hash: "TypeError"message: "detector2 is not a function"str: "detector2 is not a function"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
```

Dumping out what I'm registering to console.log right before the call, I get:

```
{id: 'zenuml', detector: ƒ, loader: ƒ}
detector : (txt) => { return /^\s*zenuml/.test(txt); }
id : "zenuml"
loader :  async () => {…}
[[Prototype]] : Object
```

...so I'm pretty sure it's not a case of mangled names. 

Is https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml up to date enough?

One note is that I had to mangle the import path to get a clean module mapping:

```
@JsModule("@mermaid-js/mermaid-zenuml/dist/mermaid-zenuml.core.mjs")
@JsNonModule
external val ZenUML: ExternalDiagram
```

**Comment by dontry** [comment]
Hi @reubenfirmin,  did you figure out this issue? If not, I am keen to help. Could you provide information of what version of mermaid, @mermaid-js/mermaid-zenuml did you use?
